- src/qemu.rs
There is most probably a race between when the sockets appear on the
filesystem and when QEMU is listening to the sockets. So we should retry
a few times in case we hit the race.
> Retry connecting to QMP socket

- Cargo.lock
- src/qemu.rs
- tests/fixtures/text_file.txt
- tests/helpers.rs
- tests/test.rs
It makes writing one liners much easier. You no longer have to do:
```
$ vmtest -k ./bzImage -- $(pwd)/myscript.sh
```
and can instead do:
```
$ vmtest -k ./bzImage -- ./myscript.sh
```
> Preserve cwd in guest for kernel targets 

- tests/helpers.rs
Seems to be useless and is causing errors in `Qemu::run_command()`.
So delete.
> tests: Remove chdir in setup()

- .github/workflows/rust.yml
- docs/config.md
- src/config.rs
- src/main.rs
- src/qemu.rs
- src/vmtest.rs
- tests/test.rs
Add a VMConfig struct to the config that will allow customizing the VM's CPUs, RAM, BIOS image, and additional host mounts. Further, allow passing in arbitrary QEMU arguments (if for example you want to add additional hardware).
> vmtest: Add additional config options

- src/qemu.rs
- tests/helpers.rs
- tests/test.rs
Best not to leave resources generated at runtime laying around after we're done using them.
This closes #25.
> test: qemu: Cleanup runtime resources

- Makefile
- src/qga.rs
If we connect to the QGA socket too early, the VM's QGA will never respond to us no matter how many times we write commands to it.
So, do the guest_sync first synchronously and recreate the socket each attempt until it passes. Then hand off to the thread loop.
Fixes #17
> qga: Retry the connection every second.

- Cargo.lock
- Cargo.toml
- src/qemu.rs
- src/qga.rs
I added support for merged output streams in qga in https://github.com/qemu/qemu/commit/810f677ab86e649d449233b435197552024b016d. It went in with v8.1 but somehow the docs are slightly off (says 8.0).
Either way, this gives us support for nicer output.
Before:
```
./target/debug/vmtest -k ~/scratch/bzImage-v6.2 -- "echo one; >&2 echo two; echo three"
=> bzImage-v6.2
===> Booting
===> Setting up VM
===> Running command
one
three
two
```
After:
```
./target/debug/vmtest -k ~/scratch/bzImage-v6.2 -- "echo one; >&2 echo two; echo three"
=> bzImage-v6.2
===> Booting
===> Setting up VM
===> Running command
one
two
three
```
> qga: Merge child output streams when available

- src/qemu.rs
- tests/helpers.rs
- tests/test.rs
Initial wait period was intended to be 200ms. But we were backing off before sleeping so it was in reality 400ms. Fix by moving backoff until after sleep.
Also fix typo (s -> ms).
> qga: Fix command waiting logic

- src/init/init.sh
- tests/test.rs
For process substitution to work, /dev/fd needs to be symlinked to /proc/self/fd
Without the change, the newly added `test_command_process_substitution` test would fail with:
```
---- test_command_process_substitution stdout ----
Command output=bash: line 1: cd: /tmp/.tmpr2SM0u: No such file or directory
Command output=cat: /dev/fd/63: No such file or directory
[tests/test.rs:251] get_error(recv, None) = Some(
"Command failed with 1",
)
thread 'test_command_process_substitution' panicked at 'assertion failed: dbg!(get_error(recv, None)).is_none()', tests/test.rs:251:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
test_command_process_substitution
test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 11 filtered out; finished in 2.41s …
```
> init: symlink /dev/fd to /proc/self/fd

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/main.rs
- src/qemu.rs
- src/vmtest.rs
- tests/test.rs
Insteads of mounting the local FS'root, we can do the same but in a chroot. The main benefit would be to be able to run a kernel/artifacts in a guest FS which may be different then the host FS. For instance when collecting CI artifacts and trying to reproduce locally.
CI may run in say Ubuntu 22.04 , while my host may be Fedora 38. This also opens up for a next diff where we can run againdt a foreign architecture provided that the chrrot is for that arch.
```
$ cat /etc/debian_version && RUST_LOG=debug cargo run -- -k $KERNEL_REPO/arch/x86_64/boot/bzImage -r debian 'cat /etc/debian_version'
trixie/sid
Compiling vmtest v0.8.3 (/home/chantra/devel/danobi-vmtest)
Finished dev [unoptimized + debuginfo] target(s) in 8.11s
Running `target/debug/vmtest -k …
```
> run kernel in chroot

- src/config.rs
- src/qemu.rs
- src/vmtest.rs
Qemu::new is getting unwieldy with a lot of parameters... even clippy is unhappy about it:
```
warning: this function has too many arguments (10/7)
```
Most of those parameters are essentially forwarding content from the Target/VM config.
It is easier to just pass the whole Target content so it can be passed around as needed without adding more parameters down the stack.
> Refactor args

- .github/workflows/rust.yml
Been getting a lot of the following error in CI runs lately:
[tests/test.rs:91] get_error(recv, None) = Some(
Error {
context: "Could not access KVM kernel module: Permission denied\nqemu-system-x86_64: failed to initialize kvm: Permission denied\n",
source: Error {
context: "Failed to connect QMP",
source: Os {
code: 111,
kind: ConnectionRefused,
message: "Connection refused",
},
},
},
)
It happens on and off for no good reason. No idea why. I'm guessing GHA might be slowly rolling out nested virt to non-large runners?
The fix in this commit is required for large runners to use nested virt. Maybe we need this for regular runners now.
See https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/
> ci: Set kvm perms

- .github/workflows/rust.yml
- src/init/init.sh
`/dev/kmsg` is conveniently hooked up to the host, where vmtest is listening. Rather than create yet another side channel, reuse a reliable existing one.
> Send qemu-ga logs out via /dev/kmsg

- Cargo.lock
- Cargo.toml
- src/init/command.template
- src/qemu.rs
This fixes one of the major annoyances with vmtest: that long running
commands "hang" until they are completed. With this PR, output is live
streamed so that the user can be less anxious.
This PR is easier to review per-commit.
This closes #39.
> Stream main command output to screen

- src/main.rs
- src/ui.rs
- tests/test.rs
If we don't even get to run the command because of some other issues, EX_UNAVAILABLE (which is kind of the catchall for "something happened") is returned instead.
When multiple targets are ran, we can't really know what to return.... in which case the old behaviour is kept, e.g return the number of failed runs.
Added test to validate the behaviour.
Fixes #43
> Return RC code of command when running one-liner

- src/config.rs
- tests/test.rs
While some fields are clearly non-optional (name, command), having a default implementation makes target definition less cumbersome, mostly in tests.
> [Target] implement Default

- README.md
- docs/config.md
- src/config.rs
- src/main.rs
- src/qemu.rs
Now that we can run `vmtest` within a given chroot, we could host the chroot for a foreign architecture and run a vmtest in that chroot using a kernel matching that ar hitecture.
```
$ uname -a && cat /etc/lsb-release && RUST_LOG=debug cargo run -- -a aarch64 -k arm64/kbuild-output/arch/arm64/boot/Image.gz -r ../rootfs/ubuntu-lunar-arm64/ 'uname -a && cat /etc/lsb-release'
Linux surya 6.5.0-14-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:59:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=23.10
DISTRIB_CODENAME=mantic
DISTRIB_DESCRIPTION="Ubuntu 23.10"
Finished dev [unoptimized + debuginfo] target(s) in 0.05s
Running `target/debug/vmtest -a aarch64 -k arm64/kbuild-output/arch/arm64/boot/Image.gz -r ../rootfs/ubuntu-lunar-arm64/ 'uname -a && cat …
```
> run qemu for a foreign architecture

- .github/workflows/release.yml
- scripts/build_release.sh
Build vmtest for x86_64, aarch64, and s390x.
As a side effect, x86_64 does not need a x86_64 anymore to be compiled.
Example release: https://github.com/chantra/danobi-vmtest/releases/tag/v1.0.0
> [release] Build vmtest binary for aarch64 and s390x too

- src/main.rs
- src/ui.rs
- tests/test.rs
`ui::run()` used to filter targets and call `vmtest::run_one()` using the index of the target in the resulting array.
The problem is that `self.vmtest` itself has the original list of targets, and therefore, the target index is different for `vmtest` and as seeing by `ui::run()`.
This change moved the logic of filtering targets into the config parsing logic. This way, both `ui` and `ui.vmtest` will have the same view of the targets and filtering does not need to be applied in multiple places.
Also add test to validate the behaviour.
To illustrate:
```
$ cat vmtest.toml
[[target]]
name = "test1"
kernel = "./kernels/bzImage-x86_64"
command = "echo test1"
[[target]]
name = "test2"
kernel = "./kernels/bzImage-x86_64"
command = "echo test2"
[[target]]
name = "test3"
kernel = …
```
> fix targets filtering

- scripts/build_release.sh
The image used to build the release can have an outdated apt cache. Run `apt update` before trying to install packages.
> build_release: run apt update before installs

- src/qemu.rs
The command that was printed by vmtest was not wrapping arguments in quotes. When trying to copy/paste the command, one had to find whatever was related to `-append` and wrap add quotes.
This wraps all argument in quotes so the printed command can be simply copy/pasted.
Before:
```
[16:34:03] chantra@surya:danobi-vmtest git:(master) $ RUST_LOG=debug cargo run -- -k kernels/bzImage-x86_64 "ls" 2>&1 | cat | grep invocation
[2024-01-18T00:34:10Z DEBUG vmtest::qemu] qemu invocation: qemu-system-x86_64 -nodefaults -display none -serial stdio -enable-kvm -cpu host -qmp unix:/tmp/qmp-264786.sock,server=on,wait=off -chardev socket,path=/tmp/qga-332867.sock,server=on,wait=off,id=qga0 -device virtio-serial -device virtserialport,chardev=qga0,name=org.qemu.guest_agent.0 --device virtio-serial …
```
> [debug] wrap qemu command arguments in quotes

- src/qemu.rs
- src/qga.rs
Fixes #40
When both the host and the VM are saturated, the VM may not be scheduled for a while, causing the connection to qga to timeout.
Prior to #27 the unix socket would block indefinitely.
This change brings back this behaviour while we run a command, and set the timeout back to what it was before running the command. This way, we can give a chance to the host/vm to recover.
Tested by running:
```
stress --cpu 256 --io 256 --vm 4 --vm-bytes 1024M --timeout 1000s
```
in the host, and
```
stress --cpu 512 --io 512 --vm 4 --vm-bytes 1024M --timeout 100s & while true; do date; sleep 2; done
```
in the guest.
Output showsa that the VM was struggling to run its loop and print the date until the stress tool was done:
```
===> Setting up VM
[    1.840931] 9pnet: Limiting 'msize' to 512000 as …
```
> run_command: wait for command to run indefinitely

- Cargo.lock
- Cargo.toml
- README.md
- src/init/init.sh
- src/main.rs
- src/qemu.rs
- tests/test.rs
When the magic command `-` is passed, and we are running in kernel mode, get a
shell prompt in the VM.
To do this, we can re-use the existing `run` framework with some changes:
- standard streams to the qemu command are not changed and instead are inherited
- child std is not streamed to the UI anymore.
- the command is not sent over qga anymore, we just wait for the qemu command to
return (e.g when user exit its bash prompt) and exit
Fixes #54
Tested by running
```
RUST_LOG=debug cargo run -- -k kernels/bzImage-x86_64 -
```
and confirming no existing tests are broken.
Also could get it to work cross-platform:
```
cargo run --  -k ./kernels/Image-arm64 -r ./rootfs/ubuntu-lunar-arm64 -a aarch64 -
```
> Drop in Interactive shell

- src/qemu.rs
cache=loose or cache=fscache currently do not validate via host, which means that a file modified on the host does not mirror back in the guest without doing some deletion dance....
https://lore.kernel.org/lkml/CAFkjPTmVbyuA0jEAjYhsOsg-SE99yXgehmjqUZb4_uWS_L-ZTQ@mail.gmail.com/ 
mmap mode seems to be needed for `mmap` to actually work per https://wiki.qemu.org/Documentation/9p_root_fs#Boot_the_9p_Root_FS_System
Fixes #61
> Set 9pfs mount cache option to mmap

- src/qemu.rs
Output of the qemu process on stderr is only captured when running in non-interactive mode. However, the error reporting infrastructure always assumes that it is being captured. As a result, we may see a panic instead of a proper error report when, for one reason or another, Qemu fails to start (as an example).
Fix the issue by making sure to always capture stderr. I haven't found any adverse effects of doing so in my admittedly limited testing.
Closes: #70
> Always capture stderr

- src/main.rs
As of Rust 1.70 (already the program's stated minimum supported Rust version), the standard library supports checking whether an input/output stream is attached to a terminal. That seems to be exactly what console::user_attended() does (in a rather non-descript way, if you ask me).
Switch to using functionality directly provided by the standard library to minimize unnecessary dependencies and make the code clearer.
> Replace usage of console::user_attended()

- src/init/init.sh
Previously we mounted a new tmpfs inside the guest at /tmp, hiding the host /tmp. Originally this was to provide a measure of separation between host and guest, as guest likely needs a writable /tmp and by default rootfs was read-only.
Over time we moved towards less of a strict separation. These days, vmtest kernel targets exist to run the existing userspace on a different kernel. To that end, we should inherit the host /tmp.
Note we keep the mount over /run, as /run usually requires root to write. Since vmtest is run as normal user, the guest naturally cannot write to host /run. Notably qemu-guest-agent tries to create /var/run/qemu-ga.pid. So keep existing logic in place.
This closes #76.
> init: Do not mount over host /tmp in guest

- docs/config.md
Sometimes toml can be a bit obtuse. Examples help a lot.
> doc: config: Start examples section

- Cargo.lock
- Cargo.toml
- src/init/init.sh.template
- src/qemu.rs
Currently all kernel target commands use host environment variables. However, init.sh uses a hard coded $PATH. This gap is most noticible on nix/nixos systems b/c nothing exists in the hard coded path. So kernel target guests are unable to find qemu-ga.
Plug this gap by templatizing init.sh and filling in with host $PATH.
Note init.sh.template now needs to be careful about escaping `{`, as that's reserved by TinyTemplate now.
This closes #79.
> init: Use host $PATH in init.sh

- src/qemu.rs
PathBuf::push(), when provided with an absolute path, will just replace the "self" path with said absolute path. This is precisely what is happening inside gen_sock(), although not intentionally. There is no need to push anything: we already formatted the full absolute path. Just convert the string into a path.
> Simplify gen_sock() helper

- scripts/docker/Dockerfile.kernel
When building multiple kernels on the same machine, docker has to rebuild the layers over and over because the values of KERNEL_TAG/DISTRO have changed (and would be the same of KERNEL_REPO was modified).
By moving them *after* the package installation, it does speed up the turnover.
> build_kernel: Speed up docker image creation

- src/qemu.rs
It seems odd to use `--device` in some places and `-device` in others. It's also not in line with our usage of other Qemu options, which all use a single dash (for better or worse).
Change `--device` to `-device` for consistency.
> Use single dash -device option

- src/qemu.rs
- src/vmtest.rs
We the Qemu::new() constructor might as well just consume the Target object, given that it won't be used afterwards. Adjust the signature and then just pull out the members we need instead of cloning them, removing a bunch of unnecessary allocations.
Similarly, the CommandContext that we instantiate just for the sake of conveying some data to the template does not need to contain any owned objects. So just work with references to existing ones, eliminating a bunch of more clones.
> Remove a bunch more clones

- src/qemu.rs
Re-using the options used in https://lore.kernel.org/all/20240905081401.1894789-10-pulehui@huaweicloud.com/ add support for running vmtest against a riscv64 target.
Tested by running:
```
cargo run -- \
-k /tmp/kbuild-riscv64/arch/riscv/boot/Image \
-r ../libbpf-ci/libbpf-vmtest-rootfs-2024.09.09-noble-riscv64 \
-a riscv64 \
'uname -a'
```
Which generated https://gist.github.com/chantra/c595fa58ef6fdc72f567e21c1c207e15
/tmp/kbuild-riscv64/arch/riscv/boot/Image is a kernel cross-compiled using:
```
make ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- O=/tmp/kbuild-riscv64 -j4 all
```
libbpf-vmtest-rootfs-2024.09.09-noble-riscv64 is a rootgs generated by
```
make ARCHS=riscv64
```
using https://github.com/libbpf/ci/blob/main/rootfs/ into which I chrooted and installed `qemu-guest-agent`.
> Add support for riscv64

- src/config.rs
- src/main.rs
- src/qemu.rs
I've been looking into getting `vmtest` to work on a RHEL 8 system. After some digging me and @javierhonduco did, we found that one of the issues is that RHEL's QEMU installation is substantially different from most other Linux distros, as it does not create `qemu-system-*` binaries, but instead has a binary in `/usr/libexec/qemu-kvm`. In order to further test, overriding the binary path used to find QEMU would be extremely helpful. This PR does that.
Ran this on a RHEL machine:
```
$ cargo run -- -k ~/code/lightswitch-kernels/bzImage_v6.9-rc5 "uname -r"
[...]
Finished `dev` profile [unoptimized + debuginfo] target(s) in 3.99s
Running `target/debug/vmtest -k /home/cloud-user/code/lightswitch-kernels/bzImage_v6.9-rc5 'uname -r'`
=> bzImage_v6.9-rc5
Failed to setup QEMU
Caused by:
0: Did …
```
> Added support for using a custom QEMU binary

- .github/workflows/rust.yml
- Makefile
- src/config.rs
- src/main.rs
- src/qga.rs
- tests/helpers.rs
- tests/test.rs
Currently, there are warnings on main, and none of the CI checks verify warnings. This PR:
- Fixes the warning
- Fixes other clippy checks
- Adds a lint step to CI
> Fix warnings and add CI lint checks

- src/qemu.rs
- src/qga.rs
Before, if guest panics, QgaWrapper still waits up to 60s/120s to return a failure to the user. There's no need for that. Let's make it fail fast by circuit breaking if qemu has already exited.
This closes #99.
> qga: Fail faster if guest panics

- docs/config.md
- src/vmtest.rs
When a non-default `rootfs` is used, and vmtest is run through `go test -exec`, the binary executed within the VM can't be found, because that rootfs doesn't contain the test binary compiled on the fly. So a custom mount has to be specified.
But, before that commit, if a relative `host_path` was used, it'd be passed as is to qemu, and thus would be resolved as relative to the cwd where qemu was running.
In the case of Go, if a directory was passed to `go test` (eg. `./integration/...`), and `GOTMPDIR=.` was set, Go would compile the test binary within its original cwd (eg. project root dir), and then launch vmtest in the 'directory under test' (eg. `./integration`), so the relative mount would resolve to the directory where vmtest was started (eg. `./integration`) -- a directory that …
> Resolve mounts host_path relatively to vmtest.toml

- src/init/init.sh.template
This fixes https://github.com/danobi/vmtest/issues/101 for me.
I'm not sure why I didn't used to hit this. I think the actual issue is that /var/local/run is owned by a privilged user and has no global write perms on my host system.
My confidence is not very high that I really understand this system so please review with skepticism :)
> init: Set QEMU state dir/PID file path directly

- README.md
- docs/config.md
- docs/rootfs.md
With this trick I've been able to use rootfs directories built using [mkosi](https://github.com/systemd/mkosi), without needing root on the host system.
I guess people who are running this via Docker etc effectively already have this in place.
> docs: A tip on using rootfs

- src/qga.rs
With all the debug options turned on in the kernel, it can take ~60s even on my relatively powerful machine (Ryzen 5950x). 80s ought to be enough for now.
Recently we landed a change to make the error quicker when the kernel panics, so this change in timeout shouldn't affect much.
> qga: Use 80s timeout even for KVM

- src/main.rs
- src/ui.rs
Some usability improvements. See individual commits for more details.
> ui: Usability improvements
